using System;
using System.Collections.Generic;
using System.Text;

namespace dlNetWeb
{
    public enum ParseError
    {
        None,
        AbruptClosingOfEmptyComment,
        AbruptDoctypePublicIdentifier,
        AbruptDoctypeSystemIdentifier,
        AbsenceOfDigitsInNumericCharacterReference,
        CdataInHtmlContent,
        CharacterReferenceOutsideUnicodeRange,
        ControlCharacterInInputStream,
        ControlCharacterReference,
        EndTagWithAttributes,
        DuplicateAttribute,
        EndTagWithTrailingSolidus,
        EofBeforeTagName,
        EofInCdata,
        EofInComment,
        EofInDoctype,
        EofInScriptHtmlCommentLikeText,
        EofInTag,
        IncorrectlyClosedComment,
        IncorrectlyOpenedComment,
        InvalidCharacterSequenceAfterDoctypeName,
        InvalidFirstCharacterOfTagName,
        MissingAttributeValue,
        MissingDoctypeName,
        MissingDoctypePublicIdentifier,
        MissingDoctypeSystemIdentifier,
        MissingEndTagName,
        MissingQuoteBeforeDoctypePublicIdentifier,
        MissingQuoteBeforeDoctypeSystemIdentifier,
        MissingSemicolonAfterCharacterReference,
        MissingWhitespaceAfterDoctypePublicKeyword,
        MissingWhitespaceAfterDoctypeSystemKeyword,
        MissingWhitespaceBeforeDoctypeName,
        MissingWhitespaceBetweenAttributes,
        MissingWhitespaceBetweenDoctypePublicAndSystemIdentifiers,
        NestedComment,
        NoncharacterCharacterReference,
        NoncharacterInInputStream,
        NonVoidHtmlElementStartTagWithTrailingSolidus,
        NullCharacterReference,
        SurrogateCharacterReference,
        SurrogateInInputStream,
        UnexpectedCharacterAfterDoctypeSystemIdentifier,
        UnexpectedCharacterInAttributeName,
        UnexpectedCharacterInUnquotedAttributeValue,
        UnexpectedEqualsSignBeforeAttributeName,
        UnexpectedNullCharacter,
        UnexpectedQuestionMarkInsteadOfTagName,
        UnexpectedSolidusInTag,
        UnknownNamedCharacterReference
    }
}
